<?php if ( ! defined('PUKKA_VERSION')) exit('No direct script access allowed');

global $pukka_theme_options;
$pukka_theme_options = 'eyJsb2dvX2ltZ19pZCI6IjIxNyIsInJldGluYV9sb2dvX2ltZ19pZCI6IjIxOCIsInRleHRfbG9nbyI6IiIsImZhdmljb25faWQiOiIzMTAiLCJnYV9jb2RlIjoiIiwiY29weSI6InB1a2thdGhlbWVzIFx1MDBhOSAyMDEzIiwiaGlkZV9hdXRob3IiOiJvZmYiLCJmYl91cmwiOiIjIiwidHdfdXJsIjoiIyIsInl0X3VybCI6IiMiLCJmcF9ib3hfbm8iOiI5IiwidXNlX2ZwX21hbmFnZXIiOiJvZmYiLCJmcF9pbmZpbml0ZV9zY3JvbGwiOiJvbiIsImZwX2RlZmF1bHRfYm94X3NpemUiOiIiLCJ0ZXh0X2NvbG9yIjoiIzY2NjY2NiIsImhlYWRpbmdfY29sb3IiOiIjMDcwMjExIiwibGlua19jb2xvciI6IiIsInN0cmlwZV8xX2NvbG9yIjoiIzliY2ViNCIsInN0cmlwZV8yX2NvbG9yIjoiI2RiOTNiMCIsInN0cmlwZV8zX2NvbG9yIjoiI2U4YjQ4MCIsInN0cmlwZV80X2NvbG9yIjoiIzliY2ViNCIsImJ1dHRvbl9iZ19jb2xvciI6IiM0NzQ3NDciLCJjdXN0b21fY3NzIjoiIiwidGl0bGVfZm9udCI6IiIsInRpdGxlX2ZvbnRfZWZmZWN0IjoiIiwidGV4dF9mb250IjoiIiwidGV4dF9mb250X2VmZmVjdCI6IiIsImZvcm1fZW1haWwiOiIiLCJmb3JtX3RoYW5rX3lvdSI6IlRoYW5rIHlvdSIsImZvcm1fZXJyb3IiOiJFcnJvciIsImZlYXR1cmVkX2NvbnRlbnQiOiIiLCJzaW5nbGVfYXV0aG9yX3NpdGUiOiJvZmYiLCJmcF9jb250ZW50X2NvbHVtbnMiOiI2IiwidGV4dF9sb2dvX2NvbG9yIjoiIzY2NjY2NiIsImhpZGVfbGFuZ3VhZ2VfZmxhZ3MiOiJvZmYiLCJmYWNlYm9va191cmwiOiJodHRwczpcL1wvd3d3LmZhY2Vib29rLmNvbVwvUHVra2FUaGVtZXMiLCJ0d2l0dGVyX3VybCI6Imh0dHBzOlwvXC90d2l0dGVyLmNvbVwvcHVra2F0aGVtZXMiLCJncGx1c191cmwiOiJodHRwczpcL1wvcGx1cy5nb29nbGUuY29tXC8xMTg0MDE3MjM3NTI2Nzk0MjA0NDVcL3Bvc3RzIiwieW91dHViZV91cmwiOiIjIiwidmltZW9fdXJsIjoiIyIsImxpbmtlZGluX3VybCI6IiMiLCJwaW50ZXJlc3RfdXJsIjoiIyIsInBpY2FzYV91cmwiOiIjIiwiaW5zdGFncmFtX3VybCI6IiMiLCJ0dW1ibHJfdXJsIjoiIyIsImRldmlhbnRhcnRfdXJsIjoiIiwiZHJpYmJibGVfdXJsIjoiIiwicmVkZGl0X3VybCI6IiIsInJzc191cmwiOiIjIiwic2lkZWJhcl90ZXh0X2NvbG9yIjoiIzY2NjY2NiIsInNpZGViYXJfdGV4dF9ob3ZlciI6IiM2NjY2NjYiLCJzaWRlYmFyX3N1Ym1lbnVfdGV4dF9jb2xvciI6IiM2NjY2NjYiLCJzaWRlYmFyX3N1Ym1lbnVfdGV4dF9ob3ZlciI6IiM2NjY2NjYiLCJoaWRlX2xhbmd1YWdlX3N3aXRjaGVyIjoib2ZmIiwiYW5hbHl0aWNzX2NvZGUiOiIiLCJyaWdodF9zaWRlYmFyX3dpZHRoIjoiIiwiZmFjZWJvb2tfYXBwX2lkIjoiIiwicHJpbnRfb2dfdGFncyI6Im9mZiIsInNvY2lhbF9mYl9saWtlIjoib24iLCJzb2NpYWxfdHdpdHRlciI6Im9uIiwic29jaWFsX2dwbHVzIjoib24iLCJzb2NpYWxfbGlua2VkaW4iOiJvbiIsInNvY2lhbF9waW50ZXJlc3QiOiJvbiIsInBhZ2VfZGlzYWJsZV9zaGFyZSI6Im9mZiIsInVzZV9mcF9ncmlkIjoib24iLCJzaG93X2hvbWVfcGFnZV9kYXRlIjoib2ZmIiwic2hvd19ob21lX3JpZ2h0X3NpZGViYXIiOiJvZmYiLCJmcF9iYXNpY19ib3hfd2lkdGgiOiIiLCJmcF9iYXNpY19ib3hfaGVpZ2h0IjoiIiwiZnBfYm94X21hcmdpbiI6IjUiLCJmcF9iYXNpY19ib3hfaW1hZ2Vfd2lkdGgiOiIiLCJmcF9iYXNpY19ib3hfaW1hZ2VfaGVpZ2h0IjoiIiwicG9zdF9wYWdlX2J1aWxkZXIiOiJvZmYiLCJyZXNwb25zaXZlX2Rpc3BsYXlfbG9nbyI6Im9mZiIsInJlc3BvbnNpdmVfbG9nb19pbWdfaWQiOiIiLCJjYXRlZ29yeV9ncmlkX2xheW91dCI6Im9uIiwiZ3JpZF9jYXRzIjpbIjIwIl0sImlubmVyX2dyaWRfZGVmYXVsdF9ib3hfc2l6ZSI6InNtYWxsIiwiZnJvbnRfcGFnZV9jYXRzIjoiIiwiZm9ybV9zcGFtX251bWJlcnMiOiIxLDMsNSw5IiwiZW5hYmxlX2N5cmlsbGljX2NoYXJfc2V0Ijoib2ZmIiwiaW5zdGFncmFtXzJfdXJsIjoiIn0=';

$pukka_theme_option_pages = array();

$tmp = json_decode($font_list, true);
$fonts = array();

foreach ($tmp as $k => $v) {
	$fonts[$v['css-name']] = $v['font-name'];
}

global $theme_style_settings;
$color_schemes = array();


foreach($theme_style_settings as $k => $v){
	$string = explode('_', $k);
	$string = implode(' ', $string);
	$color_schemes[$k] = $string;
}

$pukka_theme_option_pages['pukka_theme_settings_page'] = array(
	'page_title' => __('Theme settings', 'pukka'),
	'menu_title' => __('Theme settings', 'pukka'),
	'page_description' => __('Control and configure UBERGRID Theme.<br /> If you have any issues please go through Documentation or contact our support team.', 'pukka'),
	'page_slug' => 'pukka_theme_settings_page',
	'parent_page_slug' => false,
	'tabs' => array(
		array(
			'title' => __('General settings', 'pukka'),
			'icon' => 'fa-cogs',
			'fields' => array(
				array('title' => __('Logo', 'pukka'),
					'desc' => __('Upload your logo. Ideal/maximum width should be 200px.', 'pukka'),
					'type' => 'file',
					'id' => 'logo_img_id',
				),
				array('title' => __('Retina logo', 'pukka'),
					'desc' => __('Upload your double-sized logo for retina displays. Ideal/maximum width should be 400px.', 'pukka'),
					'type' => 'file',
					'id' => 'retina_logo_img_id',
				),
				array('title' => __('Plain text logo', 'pukka'),
					'desc' => __('Insert text which will be displayed if image logo is missing. Default is Site Title.', 'pukka'),
					'type' => 'text',
					'id' => 'text_logo',
				),
				array('title' => __('Plain text logo color', 'pukka'),
					'desc' => __('Color of the text logo which is displayed if image logo is missing.', 'pukka'),
					'type' => 'color-picker',
					'id' => 'text_logo_color',
					'default' => '#666666',
					'reset' => true,
				),
				array('title' => __('Logo for Mobile Menu', 'pukka'),
					'desc' => __('Logo image for Mobile Menu. Maximum/Ideal height is 36px.', 'pukka'),
					'type' => 'file',
					'id' => 'responsive_logo_img_id',
				),
				array('title' => __('Favicon', 'pukka'),
					'desc' => __('Upload your favicon image. Image pixel dimension must be in square aspect ratio (meaning height must be equal to the width). <br />Acceptable dimensions: mimumum 32x32px, maximum 64x64px.', 'pukka'),
					'type' => 'file',
					'id' => 'favicon_id',
				),
				array('title' => __('Analytics code', 'pukka'),
					'desc' => __('Paste your tracking code here. <br />(Google Analytics, AWStats, Piwick, Statcounter, ...).', 'pukka'),
					'type' => 'textarea',
					'id' => 'analytics_code',
				),
				array('title' => __('Copyright text ', 'pukka'),
					'desc' => __('If you have Copyright text insert it here. Copyright will be published bellow navigation.', 'pukka'),
					'type' => 'text',
					'id' => 'copy',
				),
				array('title' => __('Single author site', 'pukka'),
					'desc' => __('Select this feature in order to hide author\'s name from specific pages and post categories.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'single_author_site',
				),
				array('title' => __('Hide language switcher', 'pukka'),
					'desc' => __('Select this feature in order to hide default language switcher (flags).', 'pukka'),
					'type' => 'checkbox',
					'id' => 'hide_language_switcher',
				),
				array('title' => __('Right sidebar width', 'pukka'),
					'desc' => __('Here you can select the right sidebar width.', 'pukka'),
					'type' => 'select',
					'subtype' => 'range',
					'min' => 100,
					'max' => 500,
					'increment' => 10,
					'id' => 'right_sidebar_width',
				),
				array('title' => __('Use page builder in posts', 'pukka'),
					'desc' => __('Select this feature in order to enable using page builder in posts.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'post_page_builder',
				),
				array('title' => __('Use grid layout for categories', 'pukka'),
					'desc' => __('Select this in case you want to have grid layout for categories.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'category_grid_layout',
				),
				array('title' => __('Use grid layout for categories', 'pukka'),
					'desc' => __('Select for which categories you want to use grid layout. It will be used for all if no category is selected.', 'pukka'),
					'type' => 'select',
					'subtype' => 'cat',
					'no_default_text' => true,
					'multiple' => 5,
					'id' => 'grid_cats',
					'reset' => false,
					'empty_value' => 'None'
				),
				array('title' => __('Default category Box Size', 'pukka'),
					'desc' => __('Select default Box Size for categories. This is important if you are using grid layout for categories.', 'pukka'),
					'type' => 'select',
					'id' => 'inner_grid_default_box_size',
					'options' => array('big' => 'Big', 'medium' => 'Medium', 'small' => 'Small'),
					'reset' => true,
				),
				array('title' => __('Read more', 'pukka'),
					'desc' => __('Enter custom read more text / character.<br/>Use html entities: http://www.webmonkey.com/2010/02/special_characters/ <br/>You can also style this using .moretag CSS class (via "Custom CSS") ', 'pukka'),
					'type' => 'text',
					'id' => 'read_more',
				),
				array('title' => __('Popup submenu', 'pukka'),
					'desc' => __('Select this option if you want submenu in left sidebar to be shown in popup bouble.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'popup_submenu_enable',
				),
			),
		), // end tab General Settings
		array(
			'title' => __('Social', 'pukka'),
			'icon' => 'fa-users',
			'fields' => array(
				array('title' => __('Social buttons', 'pukka'),
					'type' => 'heading',
				),
				/*
				array('title' => __('Facebook Admins', 'pukka'),
					'desc' => __('FB IDevi korisnika', 'pukka'),
					'type' => 'text',
					'id' => 'facebook_admins',
				),
				*/
				array('title' => __('Facebook App ID', 'pukka'),
					'desc' => __('Insert your Facebook App ID. This means you now need to create a Facebook app to perform integration. <br /><br/ >Don\'t worry, creating an app is easy, you don\'t need to be a developer to create an app here. <br />Visit <a href="https://developers.facebook.com/apps/">https://developers.facebook.com/apps/</a> and click create new app.', 'pukka'),
					'type' => 'text',
					'id' => 'facebook_app_id',
				),
				array('title' => __('Enable Facebook Open Graph Tags', 'pukka'),
					'desc' => __('If you are using some other Social plugin, then you may want to disable this.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'print_og_tags',
				),
				array('title' => __('Facebook like button', 'pukka'),
					'desc' => __('Add Facebook "Like" Button to Each Post/Page', 'pukka'),
					'type' => 'checkbox',
					'id' => 'social_fb_like',
				),
				array('title' => __('Tweet button', 'pukka'),
					'desc' => __('Add Tweet Button to Each Post/Page', 'pukka'),
					'type' => 'checkbox',
					'id' => 'social_twitter',
				),
				array('title' => __('Google+ button', 'pukka'),
					'desc' => __('Add Google+ Button to Each Post/Page', 'pukka'),
					'type' => 'checkbox',
					'id' => 'social_gplus',
				),
				array('title' => __('LinkedIn button', 'pukka'),
					'desc' => __('Add LinkedIn Button to Each Post/Page', 'pukka'),
					'type' => 'checkbox',
					'id' => 'social_linkedin',
				),
				array('title' => __('Pinterest button', 'pukka'),
					'desc' => __('Add Pinterest Button to Each Post/Page', 'pukka'),
					'type' => 'checkbox',
					'id' => 'social_pinterest',
				),
				array('title' => __('Disable social buttons on Pages', 'pukka'),
					'desc' => __('Choose this option in order to disable social buttons on Pages.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'page_disable_share',
				),
				array('title' => __('Add links to your Social Networks', 'pukka'),
					'type' => 'heading',
				),
				array('title' => __('Facebook URL', 'pukka'),
					'desc' => __('Facebook Fan Page URL.', 'pukka'),
					'type' => 'text',
					'id' => 'facebook_url',
				),
				array('title' => __('Twitter URL', 'pukka'),
					'desc' => __('Twitter account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'twitter_url',
				),
				array('title' => __('Google+ URL', 'pukka'),
					'desc' => __('Google+ account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'gplus_url',
				),
				array('title' => __('Soundcloud URL', 'pukka'),
					'desc' => __('Soundcloud account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'soundcloud_url',
				),
				array('title' => __('Youtube URL', 'pukka'),
					'desc' => __('Youtube account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'youtube_url',
				),
				array('title' => __('Vimeo URL', 'pukka'),
					'desc' => __('Youtube account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'vimeo_url',
				),
				array('title' => __('LinkedIn URL', 'pukka'),
					'desc' => __('LinkedIn account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'linkedin_url',
				),
				array('title' => __('Pinterest URL', 'pukka'),
					'desc' => __('Pinterest account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'pinterest_url',
				),
				array('title' => __('Picasa URL', 'pukka'),
					'desc' => __('Picasa account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'picasa_url',
				),
				array('title' => __('Instagram URL', 'pukka'),
					'desc' => __('Instagram account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'instagram_url',
				),
				array('title' => __('Tumblr URL', 'pukka'),
					'desc' => __('Tumblr account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'tumblr_url',
				),
				array('title' => __('Flickr URL', 'pukka'),
					'desc' => __('Flickr account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'flickr_url',
				),
				array('title' => __('Deviantart URL', 'pukka'),
					'desc' => __('Deviantart account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'deviantart_url',
				),
				array('title' => __('Dribbble URL', 'pukka'),
					'desc' => __('Dribbble account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'dribbble_url',
				),
				array('title' => __('Reddit URL', 'pukka'),
					'desc' => __('Reddit account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'reddit_url',
				),
				array('title' => __('Behance URL', 'pukka'),
					'desc' => __('Behance account URL.', 'pukka'),
					'type' => 'text',
					'id' => 'behance_url',
				),
				array('title' => __('RSS URL', 'pukka'),
					'desc' => __('RSS URL.', 'pukka'),
					'type' => 'text',
					'id' => 'rss_url',
				),
				array('title' => __('Custom icons', 'pukka'),
						'desc' => __('You can add your custom icons here, for example: <br /> &lt;a target=&quot;_blank&quot; href=&quot;YOUR_URL&quot;&gt;&lt;img src=&quot;ICON_URL&quot; width=&quot;20&quot; height=&quot;20&quot; /&gt;&lt;/a&gt;', 'pukka'),
						'type' => 'textarea',
						'id' => 'custom_social_links',
				),
			),
		), // end tab Social
		array(
			'title' => __('Home page content', 'pukka'),
			'icon' => 'fa-home',
			'fields' => array(
				array('title' => __('Front page grid display', 'pukka'),
					'desc' => __('Check this box if you want front page to use grid based dispaly.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'use_fp_grid',
				),
				array('title' => __('Use Front Page Manager', 'pukka'),
					'desc' => __('Select this feature in order to manage front page boxes from Front Page Manager. In case you don\'t select this option, latest posts will be published on your front page.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'use_fp_manager',
				),
				array('title' => __('Enable infinite scroll', 'pukka'),
					'desc' => __('Choose this feature in order to enable infinite scroll (endless page) on your homepage.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'fp_infinite_scroll',
				),
				array('title' => __('Max number of front page boxes', 'pukka'),
					'desc' => __('Set up maximum number of boxes on your homepage. <br />Also, this number is the number of boxes loaded when using infinite scroll.', 'pukka'),
					'type' => 'select',
					'id' => 'fp_box_no',
					'subtype' => 'range',
					'min' => 1,
					'max' => 20,
					'reset' => true,
				),
				array('title' => __('Max front page width', 'pukka'),
					'desc' => __('Set up maximum width for your front page by choosing number of columns. One column equals small or medium box width.', 'pukka'),
					'type' => 'select',
					'id' => 'fp_content_columns',
					'options' => array('Full width', '1 column', '2 columns', '3 columns', '4 columns', '5 columns', '6 columns', '7 columns'),
					'no_default_text' => true,
				),
				array('title' => __('Default Box Size', 'pukka'),
					'desc' => __('Choose default box size. We would recommend you choose this, especially if you use infinite scroll or latest posts.', 'pukka'),
					'type' => 'select',
					'id' => 'fp_default_box_size',
					'options' => array('big' => 'Big', 'medium' => 'Medium', 'small' => 'Small', 'random' => 'Random'),
					'reset' => true,
				),
				array('title' => __('Home page Box Date', 'pukka'),
					'desc' => __('Choose do you want to show Dates of Posts/Pages on Home page Boxes.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'show_home_page_date',
					'reset' => true,
				),
				array('title' => __('Right sidebar on Front Page', 'pukka'),
					'desc' => __('Choose do you want to enable Right sidebar on Front Page.', 'pukka'),
					'type' => 'checkbox',
					'id' => 'show_home_right_sidebar',
					'reset' => true,
				),
				array('title' => __('Front Page Categories', 'pukka'),
					'desc' => __('If you want to show only latest posts from certain categories on your homepage, then you can select categories here. Keep in mind that this will work only if you aren\'t using Front Page Manager.', 'pukka'),
					'type' => 'select',
					'subtype' => 'cat',
					'no_default_text' => true,
					'multiple' => 5,
					'id' => 'front_page_cats',
					'reset' => false,
					'empty_value' => 'All'
				),
				array('title' => __('Block sizes', 'pukka'),
					'type' => 'heading',
				),
				array('title' => '',
					'desc' => '',
					'type' => 'custom-html',
					'content' => __('<strong>Here you can change block width, height, margin, image width and image height. You should be careful with this, because it will re-size your images, so don\'t change it if there isn\'t good reason.</strong>', 'pukka'),
					'css_classes' => 'two-cols input-short',
				),
				array('title' => '',
					'desc' => '',
					'type' => 'custom-html',
					'content' => __('<strong>Keep in mind that you are changing medium box (basic box), and that other box sizes are calculated automatically from this setting, so choose wisely.</strong>', 'pukka'),
					'css_classes' => 'two-cols input-short',
				),
				array('title' => __('Basic Block Width', 'pukka'),
					'desc' => __('This setting changes the width of the medium box. Other box sizes are calculated automatically from this setting, so choose wisely.  Default width is 225px.', 'pukka'),
					'type' => 'select',
					'subtype' => 'range',
					'id' => 'fp_basic_box_width',
					'min' => 150, 
					'max' => 1000, 
					'increment' => 10,
					'reset' => true,
				),				
				array('title' => __('Basic Block Height', 'pukka'),
					'desc' => __('This setting changes the width of the medium box. Other box sizes are calculated automatically from this setting, so choose wisely.  Default width is 500px.', 'pukka'),
					'type' => 'select',
					'subtype' => 'range',
					'id' => 'fp_basic_box_height',
					'min' => 150, 
					'max' => 1000, 
					'increment' => 10,
					'reset' => true,
				),
				array('title' => __('Block margin', 'pukka'),
					'desc' => __('Select spacing between blocks on front page. Default block margin is 5px.', 'pukka'),
					'type' => 'select',
					'subtype' => 'range',
					'id' => 'fp_box_margin',
					'min' => 0,
					'max' => 50, 
					'increment' => 5,
					'reset' => true,
				),
				array('title' => __('Basic block image width', 'pukka'),
					'desc' => __('Here you can choose Basic block image width. Other box sizes are calculated automatically from this setting, so choose wisely. This should be the same number as "Basic block width" option, but, it\'s your choice. Default width is 225px.', 'pukka'),
					'type' => 'select',
					'subtype' => 'range',
					'id' => 'fp_basic_box_image_width',
					'min' => 50, 
					'max' => 1000, 
					'increment' => 10,
					'reset' => true,
				),				
				array('title' => __('Basic block image height', 'pukka'),
					'desc' => __('Here you can choose Basic block image height. Other box sizes are calculated automatically from this setting, so choose wisely. Default height is 290px.', 'pukka'),
					'type' => 'select',
					'subtype' => 'range',
					'id' => 'fp_basic_box_image_height',
					'min' => 50, 
					'max' => 1000, 
					'increment' => 10,
					'reset' => true,
				),
			),
		), // end tab Front page content
		array(
			'title' => __('Style', 'pukka'),
			'icon' => 'fa-pencil',
			'fields' => array(
				array('title' => __('Theme color scheme', 'pukka'),
					'desc' => __('You can change entire theme color scheme here.', 'pukka'),
					'type' => 'select',
					'id' => PUKKA_THEME_COLORSCHEME_NAME,
					'options' => $color_schemes,
					'no_default_text' => true,
					'reset' => true,
					'default' => 'none',
				),
				array('title' => __('Text color', 'pukka'),
					'desc' => __('Body text color.', 'pukka'),
					'type' => 'color-picker',
					'id' => 'text_color',
					'default' => $pukka_theme_default_values['text_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Heading color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'heading_color',
					'default' => $pukka_theme_default_values['heading_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Link color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'link_color',
					'default' => $pukka_theme_default_values['link_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Big brick stripe color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'stripe_1_color',
					'default' => $pukka_theme_default_values['stripe_1_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Medium brick stripe color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'stripe_2_color',
					'default' => $pukka_theme_default_values['stripe_2_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Small brick stripe color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'stripe_3_color',
					'default' => $pukka_theme_default_values['stripe_3_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Featured image stripe color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'stripe_4_color',
					'default' => $pukka_theme_default_values['stripe_4_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Button color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'button_bg_color',
					'default' => $pukka_theme_default_values['button_bg_color'],
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Sidebar menu text color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'sidebar_text_color',
					'default' => '#666666',
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Sidebar menu hover text color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'sidebar_text_hover',
					'default' => '#666666',
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Sidebar submenu text color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'sidebar_submenu_text_color',
					'default' => '#666666',
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Sidebar submenu hover text color', 'pukka'),
					'desc' => '',
					'type' => 'color-picker',
					'id' => 'sidebar_submenu_text_hover',
					'default' => '#666666',
					'reset' => true,
					'css_classes' => 'two-cols input-short'
				),
				array('title' => __('Custom CSS', 'pukka'),
					'desc' => __('If you have some CSS changes enter them here or use the custom .css file', 'pukka'),
					'type' => 'textarea',
					'id' => 'custom_css',
				),
				array('title' => __('Custom JS', 'pukka'),
					'desc' => __('If you have some JS that you want to add, you can add it here. Do not surround your code with &lt;script&gt; tags, it will brake the code.', 'pukka'),
					'type' => 'textarea',
					'id' => 'custom_js',
				),
			),
		), // end tab Style
		array(
			'title' => __('Typography', 'pukka'),
			'icon' => 'fa-font',
			'fields' => array(
				array('title' => __('Title Font', 'pukka'),
					'type' => 'heading',
				),
				array('title' => __('Change Title Font', 'pukka'),
					'desc' => __('You can change title font here. Simply select a different font from the font drop-down menu', 'pukka'),
					'type' => 'select',
					'id' => 'title_font',
					'options' => $fonts,
					'reset' => true,
				),
				array('title' => __('Title Font Effect', 'pukka'),
					'desc' => __('Choose effect for your title font (Warning: all effects are not supported in all browsers).', 'pukka'),
					'type' => 'select',
					'id' => 'title_font_effect',
					'options' => $font_effects,
					'reset' => true,
				),
				array('title' => __('Text Font', 'pukka'),
					'type' => 'heading',
				),
				array('title' => __('Change Text Font', 'pukka'),
					'desc' => __('You can change text font here. Simply select a different font from the font drop-down menu.', 'pukka'),
					'type' => 'select',
					'id' => 'text_font',
					'options' => $fonts,
					'reset' => true,
				),
				array('title' => __('Text Font Effect', 'pukka'),
					'desc' => __('Choose effect for your text font (Warning: all effects are not supported in all browsers).', 'pukka'),
					'type' => 'select',
					'id' => 'text_font_effect',
					'options' => $font_effects,
					'reset' => true,
				),
				array('title' => __('Add cyrillic character set', 'pukka'),
					'desc' => __('Choose this option to enable cyrillic characters in you google fonts. (Note that not all google fonts support cyrillic character set)', 'pukka'),
					'type' => 'checkbox',
					'id' => 'enable_cyrillic_char_set',
					'reset' => true,
				),
			),
		), // end tab Typography
		array(
			'title' => __('Forms', 'pukka'),
			'icon' => 'fa-files-o',
			'fields' => array(
				array('title' => __('Email', 'pukka'),
					'desc' => __('Add your email address here. All emails from custom Forms (Page Builder) will be sent to this address.', 'pukka'),
					'type' => 'text',
					'id' => 'form_email',
				),
				array('title' => __('Thank you notification', 'pukka'),
					'desc' => __('Insert text for your "Thank You" page here. For example: Thanks for getting in touch! We\'ll reach out to you within 24 hours either by phone or email!.', 'pukka'),
					'type' => 'text',
					'id' => 'form_thank_you',
				),
				array('title' => __('Error notification', 'pukka'),
					'desc' => __('Add text that will be displayed in case error occurred during form submission.', 'pukka'),
					'type' => 'text',
					'id' => 'form_error',
				),
				array('title' => 'SPAM check',
							'desc' => 'Enter 4 comma separated numbers here, between 1 and 10, to enable spam check for your contact forms (for example: 1,3,5,9)',
							'type' => 'text',
							'id' => 'form_spam_numbers',
					),
			),
		), // end tab Forms
		array(
			'title' => __('Content importer', 'pukka'),
			'icon' => 'fa-exclamation-circle',
			'fields' => array(
				array('title' => __('Pukka demo content importer', 'pukka'),
					'desc' => __('This is importer for theme demo content. Please only use it on fresh WordPress installs with empty database. Otherwise, results might be somewhat unexpected.', 'pukka'),
					'type' => 'custom-html',
					'content' => '<div class="import-controls">
									<img class="waiting" id="waiting-import" style="display:none;" src="' . admin_url('images') . '/wpspin_light.gif" alt="" />
									<div class="pukka-button-primary" id="pukka-import">Start import</div>									
								</div>
								<div id="pukka-import-frame"></div>'
				)
			),
		), // end tab Forms
	) // close tabs
);
